# Общие переменные
node_exporter_port: 9100
nginxlog_exporter_port: 4040

# Prometheus scrape targets (подставите реальные private IP ваших web)
web_targets:
  - host: "10.20.0.13"
  - host: "10.21.0.3"

elasticsearch_host: "10.20.0.28"
elasticsearch_port: 9200

grafana_admin_password: "ChangeMe123!"
