---
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
    update_cache: true

- name: Add Grafana APT key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true

- name: Set admin password
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;?admin_password\s*='
    line: "admin_password = {{ grafana_admin_password }}"
  notify: Restart grafana

- name: Enable and start grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
