---
- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present
    update_cache: true

- name: Configure prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  notify: Restart prometheus

- name: Enable and start prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
